fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'no-reply@localhost'
        sender_name: 'no-reply'
    registration:
        confirmation:
            enabled: true
    service:
        mailer: fos_user.mailer.noop
