doctrine:
    dbal:
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
        mapping_types:
            uuid_binary_ordered_time: binary