fos_user_security_login:
    methods: ['GET']
    path: /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    methods: ['POST']
    path: /admin/login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    methods: ['GET', 'POST']
    path: /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /admin/profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile