easy_admin:
    list:
        actions: ['show', 'edit', 'delete']
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - username
                    - fullname
                    - email
                    - { property: 'avatar', type: 'image' }
                    - securityRoles
                    - enabled
                    - superAdmin
            form:
                fields:
                    - fullname
                    - username
                    - email
                    - avatar
                    - enabled
                    - superAdmin
                    - lastLogin
                    - securityRoles
                    - { property: plainPassword,
                        type: 'text',
                        type_options: {
                            required: false
                        } }
        Project:
            class: App\Entity\Project
            list:
                fields:
                    - name
                    - author
                    - url
                    - teams
                    - createdAt
            form:
                fields:
                    - name
                    - description
                    - url
                    - author
                    - teams
        Article:
            class: App\Entity\Article
            list:
                fields:
                    - title
                    - category
                    - author
                    - { property: 'image', type: 'image' }
                    - comments
                    - publishedAt
                    - published
            form:
                fields:
                    - title
                    - category
                    - image
                    - description
                    - content
                    - tags
                    - author
            edit:
                fields:
                    - published
        Tag:
            class: App\Entity\Tag
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name
        Category:
            class: App\Entity\Category
            list:
                fields:
                    - name
                    - code
            form:
                fields:
                    - name
        SecurityRole:
            class: App\Entity\SecurityRole
            list:
                fields:
                    - name
                    - role
                    - users
            form:
                fields:
                    - name
                    - role
                    - { property: 'users', type_options: { by_reference: false } }
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - originalName
                    - { label: 'Image', property: url, type: 'image' }
                    - author
                    - uploadedAt
                    - createdAt
                    - updatedAt
            show:
                fields:
                    - id
                    - author
                    - { label: 'Size (in bytes)', property: size }
                    - originalName
                    - { property: 'url', type: 'url' }
                    - uploadedAt
                    - createdAt
                    - updatedAt
                    - { label: 'Image', property: 'fileName', type: 'image', base_path: '/media/upload' }
            form:
                fields:
                    - author
                    - { property: 'file', type: 'vich_image' }
            edit:
                fields:
                    - originalName
        Comment:
            class: App\Entity\Comment
            form:
                fields:
                    - article
                    - author
                    - text

        CommentReply:
            class: App\Entity\CommentReply
            form:
                fields:
                    - comment
                    - author
                    - text
        Team:
            class: App\Entity\Team
            form:
                fields:
                    - name
                    - parent
                    - users